logging:
  level:
    root: info

spring:
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui
  liquibase:
    change-log: 'classpath:db/changelog-master.xml'
    enabled: true

com.kulsin.wallet:
  username: test
  password: test
